---
- name: Setup Web Server
  hosts: webservers
  become: yes
  vars:
    domain: techcorp.com
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy Apache config
      copy:
        content: |
          <VirtualHost *:80>
              ServerName {{ domain }}
              DocumentRoot /var/www/html
          </VirtualHost>
        dest: /etc/apache2/sites-available/{{ domain }}.conf
      notify:
        - Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

- name: Setup Database Server
  hosts: dbservers
  become: yes
  vars:
    postgresql_version: "14"
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql-{{ postgresql_version }}
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: true
